apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: staging
spec:
  encryptedData:
    value: AgCZrdDAPm5rcvuY+PIsRo7dy5HGt/OjkBJgZ1ewxpsQKs/gysxxkooY9GfNG94i+Ljcz4trCmm8kksfg743aNdnZull2uaIO4wS2GE+afUpRYhkJ6yZp0+nBPaGsxL0a0wb7fCkIFL6wrmiygqryssVFZxGCdbGwXdReiKI0xC/rQEqaeioep6T45qfOaZUd3ba1fzm5gDOlSpVS5FA/wzLNDtVNwKJTyR9KUlF9YAxynnxDE1HW7ErMqHJNnhXqpTB49L8W0JXbIaO1USOuRksCk/YoEd3tn0Cha7NBECqEWbQ20cXaS8m8bd8jxmOMJ63dvnz9EllZGowavlVTioWy6jw9sdl5JqdTc/322h5cvqEVkmAgExBHIMMhE0C2r8WaIbP9KDXbHXSbiM/oF0XPKEMdL7ssL3EN5+NNZEv8p3MtMHg2yUMHLm/sv7Nq14f5YNsotumfUIb/RUrWve+cdCvXGgJ2bnjexJVIEwORj09FFKBAxwD9/+qa6HCnuPXFamz1SG95oGEWipvP6bHc+KNnI6HpsSu8oqVfhIJkvGos10JhaSdm/92OzFdu3BQykLOdEbrLti8CfC704VLTN9mKfgQiabj9lAa0BvREYLFOHxcQX3bdEKbTb0q+n7RapqeJPzzUgbU3X7S00VLk+UAjT3fTrnOL0MBDEGPNuu/m/m/nZJ0czTb5f1b+7wrvwVxuf2WSBjWABjnUBT2V+Qr7DMq2Egio/7Kug==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: staging

