apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: dev
spec:
  encryptedData:
    value: AgBdObz3XxkNxyVsmWJA2K/3HHIEWfJMKcNX+Lh71ZmBhc8/HTC9Dw3MhoHKnHJZlvOpvN93FBjbO+1C0+IPsKr/KEEKsACrinkqii46BofZJy9jKYFj9USWkf5ashgb3o6EGTEIL4tjmy8Oj/K48KlAGGzo6m14rnlbRsMGrNvT/phAdIyJVKhapF9B0bVT9rdj1rrPnQyuaxG4ufLC6ceHAdP/R3bqLN6rxHi94VKoOllwQ+iAQ3W6pYwTpJZhTbzcC901ur8hw/F8YoQsccKAgZzuFjDZw/que2VEQPbREy6a+A5KoYLMbqvp7XY/09M0q3qpBJqdIfwEj2Cyj2TNpTLw56SvFhqSkA8LCj0V4Zy/c5iMKOV1jUfmg105G7DAdmc98y/SAWKW7Cw1RxXJuhBDeX/ogiipUCljwLh3TJGI6ku5oM58yJgTSnIr5ji9vuhY1gYDAnD6H5q76UGnajb71afj40m0o+UkYyFNoBr8SF/8uriReAO4Dcab1qABM07Tvvk4ZSh+N1OuvEj0N81SzJJBN/OpzTFXh91Z5ZZ6QaJgqpdQY31KELbgbfGKF7eEE8EHre8f9HvGAq2cfU0x37T6IQgA4+0EGy2KLoYbHYU/aW7gSJn1ImTA/awv91/Qge7Ksc28zVDE295oJk+o1M5cxi3F/UI4+qQpJZBQGAb68P6l5jiCDS4fhtXmuYuYdAingu5/oNTycv75z+hVZOpljRgYfXbVKw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: dev

