apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-api-token
  namespace: dev
spec:
  encryptedData:
    value: AgA/rnvAsO2Fd02Ww0Kiqdpecx4zr9jrWekK4PtQcEg1OMKZAgPQqAzOZwfNbC2ao6kDjW4q0noC4kk1BinT72jKOxWJvL+cOS/6GP1pA1c65q9e/T/eYnW31MWnDp/P7KZ8AVoxQYBwLJqfV0GlfJ2LcfSoapnCzN/EphUahMN/3UNItv0SH56vd41qVCxxqnNyI6QmSBN4ROvLFIEjKD/CuzARA7J9AERl4x3Zrocv7qDdD16keWmyMdQ3/GFM1yApFOz7CfCFdU1sq4FO9M+WmGE5Tze7dBBbzrtZtOAM0HX2szb11NhormqmK0bi4e5XqT7ch5iU2RBWTlEfqXHggbiwFxutoZTf//L5+6KTPW1Mx0q9eP1P/BDl5iTuX4X9IVugx4dY7hDtsXlUmrrldZ3rMHf8KVMsFWNZD3I4Coi7IeMNC/4CpRSSpLPaNWRzG5vTdiuTV8Mg4vGFwrmp2sUIKWL6GYzJChX4x17MtAMU/+3xKtiEIzeWw9SxX93Jx+MBjd4m/dA/Egmg/50kshisnYrqMui8GBCGm9JrfuuXvhO8bTNRoBbcz8PMBh3GLMhym8+Kc9a1VZhfkB4lyK6krQZ5DAKORJ4ax066bzG5WPJYp/QXuODIacLX/Ru0ZPUEdOmAyHe8JWbQvLGs1HGRwSLkOLYC5PyuaNWb2iGuM5+cKlPNyj5VmXYjQUAbbKJl5zqHtMRuMQdMoOYvJtFFRRTsvdBa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: logging-api-token
      namespace: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
  namespace: dev
spec:
  encryptedData:
    value: AgBdObz3XxkNxyVsmWJA2K/3HHIEWfJMKcNX+Lh71ZmBhc8/HTC9Dw3MhoHKnHJZlvOpvN93FBjbO+1C0+IPsKr/KEEKsACrinkqii46BofZJy9jKYFj9USWkf5ashgb3o6EGTEIL4tjmy8Oj/K48KlAGGzo6m14rnlbRsMGrNvT/phAdIyJVKhapF9B0bVT9rdj1rrPnQyuaxG4ufLC6ceHAdP/R3bqLN6rxHi94VKoOllwQ+iAQ3W6pYwTpJZhTbzcC901ur8hw/F8YoQsccKAgZzuFjDZw/que2VEQPbREy6a+A5KoYLMbqvp7XY/09M0q3qpBJqdIfwEj2Cyj2TNpTLw56SvFhqSkA8LCj0V4Zy/c5iMKOV1jUfmg105G7DAdmc98y/SAWKW7Cw1RxXJuhBDeX/ogiipUCljwLh3TJGI6ku5oM58yJgTSnIr5ji9vuhY1gYDAnD6H5q76UGnajb71afj40m0o+UkYyFNoBr8SF/8uriReAO4Dcab1qABM07Tvvk4ZSh+N1OuvEj0N81SzJJBN/OpzTFXh91Z5ZZ6QaJgqpdQY31KELbgbfGKF7eEE8EHre8f9HvGAq2cfU0x37T6IQgA4+0EGy2KLoYbHYU/aW7gSJn1ImTA/awv91/Qge7Ksc28zVDE295oJk+o1M5cxi3F/UI4+qQpJZBQGAb68P6l5jiCDS4fhtXmuYuYdAingu5/oNTycv75z+hVZOpljRgYfXbVKw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-password
      namespace: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blue
  name: blue
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
        resources: {}
        env:
          - name: LOGGING_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: logging-api-token
                key: value
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-password
                key: value
status: {}
