apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blue
  name: blue
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
        resources: {}
        env:
          - name: LOGGING_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: logging-api-token
                key: value
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-password
                key: value
status: {}
